### ISSUE TITLE
Adding zig to rosetta code

### ISSUE THREAD

**Issue by benjif** [tiehuis/zig-rosetta#2]
I'm not sure if this has been discussed yet, and since this repo is directly related, I'll ask it here: are we waiting until a later version to add zig to rosettacode?

https://rosettacode.org/wiki/Rosetta_Code:Add_a_Language

**Comment by tiehuis** [comment]
There is no concrete reason not to add Zig solutions. I've created a language page for now and added one simple task just for some presence.

https://rosettacode.org/wiki/Category:Zig

The main reason to possibly avoid adding lots of tasks just yet is due to language instability. I find updating pages on rosettacode a little annoying so will probably leave solutions here just for now but feel free.

**Comment by benjif** [comment]
@tiehuis Thanks for creating one, we can add some simple examples for stable parts of the language as we progress.
